# Generated by Django 5.2.5 on 2025-08-14 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Knd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url_knd', models.URLField(blank=True, default=None, help_text='Ссылка на проверку в формате https://proverki.gov.ru/...', null=True, unique=True, verbose_name='Ссылка на проверку')),
                ('number_knd', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер КНД')),
                ('status_knm', models.CharField(blank=True, default='', max_length=20, verbose_name='Статус КНМ')),
                ('reg_data', models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации КНМ')),
                ('start_data', models.DateField(blank=True, null=True, verbose_name='Начало КНМ')),
                ('end_data', models.DateField(blank=True, null=True, verbose_name='Окончание КНМ')),
                ('adress', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('departure_time', models.DateTimeField(blank=True, help_text='Формат: DD.MM.YYYY HH:MM', null=True, verbose_name='Время выезда')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knd_inspector', to=settings.AUTH_USER_MODEL, verbose_name='Инспектор')),
            ],
            options={
                'ordering': ['created', 'number_knd'],
            },
        ),
    ]
