# Generated by Django 4.2.23 on 2025-08-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url_knd', models.URLField(blank=True, default=None, help_text='Ссылка на проверку в формате https://proverki.gov.ru/...', null=True, unique=True, verbose_name='Ссылка на проверку')),
                ('number_knd', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер КНД')),
                ('status_knm', models.CharField(blank=True, default='', max_length=20, verbose_name='Статус КНМ')),
                ('reg_data', models.DateField(blank=True, null=True, verbose_name='Дата регистрации КНМ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало КНМ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание КНМ')),
            ],
            options={
                'ordering': ['created', 'number_knd'],
            },
        ),
    ]
