# Generated by Django 4.2.23 on 2025-08-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knd',
            name='reg_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации КНМ'),
        ),
    ]
