# Generated by Django 4.2.23 on 2025-08-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knd', '0002_alter_knd_reg_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knd',
            old_name='end_date',
            new_name='end_data',
        ),
        migrations.RenameField(
            model_name='knd',
            old_name='start_date',
            new_name='start_data',
        ),
    ]
