# Generated by Django 4.2.23 on 2025-08-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knd', '0003_rename_end_date_knd_end_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knd',
            name='departure_time',
            field=models.DateTimeField(blank=True, help_text='Формат: DD.MM.YYYY HH:MM', null=True, verbose_name='Время выезда'),
        ),
    ]
