# Generated by Django 4.2.23 on 2025-08-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knd', '0004_knd_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='knd',
            name='adress',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
    ]
